site_name: CME World Wiki
site_url: https://wiki.cmeworld.fun 

theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.tracking
        - navigation.sections
    - navigation.expand
    - search.highlight
    - toc.integrate
    - navigation.footer
  logo: assets/logo.png
  palette:
    - scheme: slate
      primary: deep purple  # можно оставить любой
      accent: deep purple
      dark: true
  font:
    code: Epunda Slab 
  font: false



extra:
  homepage: https://wiki.cmeworld.fun # опционально

plugins:
  - search
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - git-authors            # покажет авторов на странице

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  
nav:
  - Главная: index.md
  - Simple Voice Chat: Simple-Voice-Chat.md
  - Core Protect: Core-Protect.md
  - BlueMap: Bluemap.md
  - Emotecraft: Emotecraft.md
  - Кастомные крафты: Custom-craft.md
  - Система скинов: Skins-Resrtorer.md
  - Оптимизация жителей: Vilager-Trade.md
